# Generated by Django 3.2.6 on 2021-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Place name')),
                ('address', models.CharField(max_length=2014, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('district', models.CharField(max_length=1024, verbose_name='District')),
                ('state', models.CharField(max_length=1024, verbose_name='State')),
                ('country', models.CharField(max_length=1024, verbose_name='Country')),
                ('zip', models.CharField(max_length=6, verbose_name='ZIP / Postal code')),
            ],
        ),
    ]
